### ISSUE TITLE
Lot of white dots on the screen (like old CRT)

### ISSUE THREAD

**Issue by ArchTonIO** [blippy/rpi#5]
Hi :) I'm trying your library with my pico and a 128x64 OLED, I create the project and brutally copy-pasted your code (thanks you for your wok). I can't see nothing on the screen except a lot of white dots filling it and some refresh in the upper border. Any ideas on what's happening?

**Comment by blippy** [comment]
Hmmm, I think I've had some similar problems in the past on a different microcontroller. It turned out to be buggy code. However, this code should work, because I tested it.

Some things to check: are sure it's an I2C oled, and not a SPI one? Ensure that the OLED's SDA pin is connected to GPIO4, and SCL to GPIO5. Its VCC should be connected to the Pico's 3V3(OUT) on pin 36. GND goes to any GND. Also ensure that the Pico is powered through the USB port. There may not be enough power to power the oled otherwise.

If that doesn't work then test the using Micropython. Install Micropython onto the board and upload the following two files:

- https://github.com/blippy/rpi/blob/master/1306/ssd1306.py
- https://github.com/blippy/rpi/blob/master/1306/pico1306.py

Does the micropython version work but not the SDK version?

**Comment by ArchTonIO** [comment]
Thanks you for quickly replying.
I double checked the pins, and also changed the display (the are both the same) and as you can see from the link (https://www.amazon.it/gp/product/B07XRV5ZHX/ref=ppx_yo_dt_b_asin_title_o02_s01?ie=UTF8&th=1) they are i2c OLEDs.
I installed Micropython on my pico, loaded the code you linked me, and the same thing happens, but this time the screen blinks while displaying the white dots.

**Comment by blippy** [comment]
Hmmm, this suggests either a problem with either your setup, or the oled itself. 

Reconfigure your setup, and follow the instructions here:
https://www.tomshardware.com/how-to/oled-display-raspberry-pi-pico
It is also for micropython. You won't need to re-upload micropython. Does this new set of instructions work?

**Comment by ArchTonIO** [comment]
I followed the guide and I had the same results, so I tried with arduino to check the OLEDs and the same thing happens. So the screens are both faulted with no doubt (that's strange btw). sorry for the time you spent answering me. I' ll send them back to Amazon and buy new ones (working I hope). thanks you again :)
